name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: npm test
      
    - name: Build package
      run: npm run build
      
    - name: Bump version
      run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
    - name: Get new version
      id: version
      run: echo "new-version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Commit version bump
      run: |
        git add package.json
        git commit -m "chore: bump version to v${{ steps.version.outputs.new-version }}"
        git tag v${{ steps.version.outputs.new-version }}
        git push origin main
        git push origin v${{ steps.version.outputs.new-version }}
        
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.version.outputs.new-version }}
        name: Release v${{ steps.version.outputs.new-version }}
        body: |
          Release v${{ steps.version.outputs.new-version }}
          
          This release was created automatically by GitHub Actions.
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}